global:
  scrape_interval: 1s # Make scrape interval to 1s for testing.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "ese-server"
    scrape_interval: 1s
    static_configs:
      - targets:
          ["ese-server1:2001", "ese-server2:2002"]

  - job_name: "ese-server-localhost"
    scrape_interval: 1s
    static_configs:
      - targets:
          ["localhost:2001", "localhost:2002"]

  - job_name: "redis"
    scrape_interval: 1s
    static_configs:
      - targets:
          ["redis-server:6379", "host.docker.internal:6379", "localhost:6379"]
